### ISSUE TITLE
Nivel script: Aflezen van jaar en weeknummer van het nieuwe jaar (2024) gaat niet goed

### ISSUE THREAD

**Issue by Hanna-GGDHM** [ggdatascience/IZB_scripts#1]
datafiles = bind_rows(lapply(links, function (el) {
  periode = str_match(xml_text(el), "(\\d{4}).*(\\d{2})")
  return(data.frame(jaar=as.numeric(periode[,2]), week=as.numeric(periode[,3]), link=xml_attr(el, "href")))
})) %>% arrange(jaar, week)

Geeft lege jaar en week voor 2024, waardoor verderop in het script iets mis gaat met de volgorden etc.

**Comment by Hanna-GGDHM** [comment]
Ik heb het zelf nu opgelost door de str_match te vervangen:
periode = str_match(xml_text(el), "(\\d{4}).*wk(\\d+)")

**Comment by pieterseinen** [comment]
Fix toegevoegd aan main.
